name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-latest

    env:
      name: CodigoFacilito
    
    steps:
      - name: Working dir
        run: echo $GITHUB_OUTPUT

  seconds_jobs:
    needs: firts_jobs
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo Segundo
        run: echo "Hola Mundo ${{ github.ref }}"