name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}
    
    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log
      
      - name: Subir artefacto
        uses: actions/upload-artifac@v4
        with:
          name: archivo-test
          path: test.log