name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: ["Hola", "CodigoFacilito","Bootcamp GitHub Action"]

    steps:
      - name: Primer mensaje
        run: echo "${{ matrix.message}}"