name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-lastest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo"

  seconds_jobs:
    runs-on: ubuntu-lastest

    steps:
      - name: Hola Mundo Segundo
        run: echo "Hola Mundo Segundo"