name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-lastest

    env:
      name: CodigoFacilito
    
    steps:
      - name: Working dir
        run: ls -al
      
      - name: Action
        uses: actions/checkout@v4

      - name: Working dir after action
        run: ls -al

  seconds_jobs:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: firts_jobs
    runs-on: ubuntu-lastest

    steps:
      - name: Hola Mundo Segundo
        run: echo "Hola Mundo ${{ github.ref }}"