name: Deploy to server

on: push

jobs:
  firts_jobs:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    env:
      name: CodigoFacilito
    
    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT
      
      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  seconds_jobs:
    needs: firts_jobs
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.firts_jobs.outputs.salida }}

    steps:
      - name: Hola Mundo Segundo
        run: echo "$SALIDA"